package org.entermediadb.asset.modules;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.http.StatusLine;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.entermediadb.asset.MediaArchive;
import org.entermediadb.authenticate.BaseAutoLogin;
import org.entermediadb.net.HttpSharedConnection;
import org.json.simple.JSONObject;
import org.openedit.WebPageRequest;
import org.openedit.data.Searcher;
import org.openedit.profile.UserProfile;
import org.openedit.users.User;
import org.openedit.users.UserManager;
import org.openedit.users.authenticate.PasswordGenerator;

public class EnterMediaCloudModule extends BaseMediaModule
{
	private static final Log log = LogFactory.getLog(EnterMediaCloudModule.class);

	HttpSharedConnection fieldConnection;

	protected HttpSharedConnection getConnection()
	{
		//getModuleManager().getBean("searcherManager");
			//UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
		
//		User admin = (User)getSearcherManager().getData("system", "user", "admin");
//		String adminkey = userManager.getEnterMediaKey(admin);
			
			fieldConnection = new HttpSharedConnection();
//			fieldconnection.addSharedHeader("X-token", node.get("entermediakey"));
//			fieldconnection.addSharedHeader("X-tokentype", "entermedia");
		return fieldConnection;
	}

	//Give it a temporary key that is generated by the server and will be authenticated by the remote server as well
	public void loginUserWithExpiringKey(WebPageRequest inReq)
	{
		//createConnection
		//The adminkey will be defaulted for new sites. Once this is  used once we will want to change the login
		if(inReq.getUser() != null)
		{
			log.info("Already logged in as " + inReq.getUserName());
			inReq.putPageValue("status","Already logged in");	
			return;
			
		}
		
		boolean isoptions = inReq.getRequest().getMethod().equals("OPTIONS");
		if( isoptions)
		{
			//Dont redirect. Wait for CORS to run
			return;
		}
		
		//TODO: Make this expire
		String userkey = inReq.getRequestParameter("entermediacloudkey");
		if(userkey == null)
		{
			log.info("No key found " + userkey);
			inReq.putPageValue("status","No key found on request");	
			return;
		}
		String userid = userkey.substring(0,userkey.indexOf("md5"));
		
		//TODO: Make this configurable
		
		log.info("Validate user key: " +userkey + " | user: "+userid);
		
		
		JSONObject params = new JSONObject();
		params.put("accountname",userid);
		params.put("entermedia.key",userkey); //TODO: Some problem parsing this in NGINX/TOmacat without the .
		params.put("entermediakey",userkey);
		//TODO: Make sure this user is part of this collection 
		String collectionid = inReq.getRequestParameter("collectionid");
		
		MediaArchive archive = getMediaArchive(inReq);
		String workspaceid = archive.getCatalogSettingValue("workspace-id");
		if( workspaceid == null)
		{
			archive.setCatalogSettingValue("workspace-id", workspaceid);
		}
		else if( !workspaceid.equals(collectionid) )
		{
			inReq.putPageValue("status","Workspace ID does not match previous collection id");	
			return;
		}
		params.put("collectionid",collectionid);
		
		String base = archive.getCatalogSettingValue("workspace-provider-mediadb");//"https://entermediadb.org/entermediadb/mediadb";
		//String base = "http://localhost:8080/entermediadb/mediadb";
		String url = base + "/services/authentication/validateuser.json";
		CloseableHttpResponse resp = getConnection().sharedPostWithJson(url, params);
		StatusLine filestatus = resp.getStatusLine();
		if (filestatus.getStatusCode() != 200)
		{
			//Problem
			log.info( filestatus.getStatusCode() + " URL issue " + " " + url + " with " + userkey);
			inReq.setCancelActions(true);
			return;
		}
		JSONObject data = getConnection().parseJson(resp);
		String status = (String)data.get("status");
		if( "ok".equals(status))
		{
			UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
			String email = (String)data.get("email");
			
			User user = userManager.getUserByEmail(email);
			if( user == null)
			{
				user = userManager.createUser("em" + userid, null);
				user.setEmail(email);
				user.setEnabled(true);
			}
			user.setFirstName((String)data.get("firstname"));
			user.setLastName((String)data.get("lastname"));
			user.setPassword((String)data.get("password"));
			userManager.saveUser(user);

			String catalogid = inReq.findValue("catalogid");

			Searcher profilesearcher = getSearcherManager().getSearcher(catalogid, "userprofile");
			
			UserProfile userprofile = (UserProfile)profilesearcher.query().exact("userid",user.getId()).searchOne();
			if( userprofile == null)
			{
				userprofile = (UserProfile) profilesearcher.createNewData();
				userprofile.setId(user.getId());
				userprofile.setProperty("settingsgroup", "administrator"); //dependant on what what we get back from our site. On Team?
			}
			userprofile.setValue("entermediacloudkey",userkey);
			profilesearcher.saveData(userprofile);
			
			inReq.putSessionValue("systemuser", user);
			inReq.putSessionValue(catalogid + "user", user);
			inReq.putPageValue("user", user);
			
			BaseAutoLogin autologin = (BaseAutoLogin)getModuleManager().getBean(archive.getCatalogId(),"autoLoginWithCookie");
			autologin.saveCookieForUser(inReq, user);
			
		}
		else
		{
			log.info( status + " Could not login user " + userkey);
			inReq.setCancelActions(true);
		}
		inReq.putPageValue("status",status);		
	}

	public void getAdminKey(WebPageRequest inReq)
	{
			UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
			
			User user = userManager.getUser("admin");
			String password = user.getPassword();
			if( password.equals("admin") || password.equals("DES:2JPGMLB8Y60=") )
			{
				//reset their password to something better
				String tmppassword = new PasswordGenerator().generate();
				user.setPassword(tmppassword);				
			}
			
			String key = userManager.getStringEncryption().getEnterMediaKey(user);
			inReq.putPageValue("adminkey",key);
	}
	
	public boolean validateCloudKey(WebPageRequest inReq) {
		inReq.getJsonRequest();
		String userkey = inReq.getRequestParameter("entermediacloudkey");
		if(userkey == null)
		{
			log.info("No key found " + userkey);
			inReq.putPageValue("status","No key found on request");
			inReq.setCancelActions(true);
			return false;
		}
		String collectionid = inReq.getRequestParameter("collectionid");
		
		MediaArchive archive = getMediaArchive(inReq);
		String workspaceid = archive.getCatalogSettingValue("workspace-id");
		if( workspaceid == null)
		{
			archive.setCatalogSettingValue("workspace-id", collectionid);
		}
		else if( !workspaceid.equals(collectionid) )
		{
			inReq.putPageValue("status","Workspace ID does not match previous collection id");
			inReq.setCancelActions(true);
			return false;
		}

		JSONObject params = new JSONObject();
		params.put("entermedia.key",userkey);
		params.put("entermediakey",userkey);
		params.put("collectionid",collectionid);
		
		String base = archive.getCatalogSettingValue("workspace-provider-mediadb");
		
		if( base == null)
		{
			inReq.putPageValue("status","workspace-provider-mediadb is not set in catalog settings");
			inReq.setCancelActions(true);
			return false;
		}
		String url = base + "/services/authentication/validateuser.json";
		
		CloseableHttpResponse resp = getConnection().sharedPostWithJson(url, params);
		StatusLine filestatus = resp.getStatusLine();
		if (filestatus.getStatusCode() != 200)
		{
			//Problem
			log.info( filestatus.getStatusCode() + " URL issue " + " " + url + " with " + userkey);
			inReq.setCancelActions(true);
			return false;
		}
		JSONObject data = getConnection().parseJson(resp);
		String status = (String)data.get("status");
		inReq.putPageValue("status",status);
		if( "ok".equals(status))
		{			
			return true;
		}
		inReq.setCancelActions(true);
		return false;
	}
	
	public void logInAsAdmin(WebPageRequest inReq) {
		UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
		
		User user = userManager.getUser("admin");
		inReq.putPageValue("user", user);
	}
}
