package org.entermediadb.asset.modules;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.http.StatusLine;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.entermediadb.asset.MediaArchive;
import org.entermediadb.authenticate.AutoLoginResult;
import org.entermediadb.net.HttpSharedConnection;
import org.json.simple.JSONObject;
import org.openedit.WebPageRequest;
import org.openedit.users.User;
import org.openedit.users.UserManager;

public class EnterMediaCloudModule extends BaseMediaModule
{
	private static final Log log = LogFactory.getLog(EnterMediaCloudModule.class);

	HttpSharedConnection fieldConnection;

	protected HttpSharedConnection getConnection()
	{
		//getModuleManager().getBean("searcherManager");
			//UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
		
//		User admin = (User)getSearcherManager().getData("system", "user", "admin");
//		String adminkey = userManager.getEnterMediaKey(admin);
			
			fieldConnection = new HttpSharedConnection();
//			fieldconnection.addSharedHeader("X-token", node.get("entermediakey"));
//			fieldconnection.addSharedHeader("X-tokentype", "entermedia");
		return fieldConnection;
	}

	//Give it a temporary key that is generated by the server and will be authenticated by the remote server as well
	public void loginUserWithExpiringKey(WebPageRequest inReq)
	{
		//createConnection
		//The adminkey will be defaulted for new sites. Once this is  used once we will want to change the login
		
		
		//TODO: Make this expire
		String userkey = inReq.getRequestParameter("entermediacloudkey");
		String userid = userkey.substring(0,userkey.indexOf("md5"));
		
		//TODO: Make this configurabl
		
		
		//String base = "https://entermediadb.org/entermediadb/mediadb";
		String base = "http://localhost:8080/entermediadb/mediadb";
		
		String url = base + "/services/authentication/showinfo.json";
			
		JSONObject params = new JSONObject();
		params.put("userid",userid);
		params.put("entermedia.key",userkey); //This should be expiring
		CloseableHttpResponse resp = getConnection().sharedPostWithJson(url, params);
		StatusLine filestatus = resp.getStatusLine();
		if (filestatus.getStatusCode() != 200)
		{
			//Problem
			log.info("URL issue " + " " + url + " with " + userkey);
		}
		JSONObject data = getConnection().parseJson(resp);
		String status = (String)data.get("status");
		if( "ok".equals(status))
		{
			UserManager userManager = (UserManager) getModuleManager().getBean("system", "userManager");
			String email = (String)data.get("email");
			
			User user = userManager.getUserByEmail(email);
			if( user == null)
			{
				user = userManager.createUser(userid, null);
				user.setEmail(email);
			}
			user.setFirstName((String)data.get("firstname"));
			user.setLastName((String)data.get("lastname"));
			userManager.saveUser(user);
			
			inReq.putSessionValue(inReq.findValue("catalogid") + "user", user);
			inReq.putPageValue("user", user);
		}
		else
		{
			log.info("Could not login user " + userkey);
		}
	}

}
