// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectCtrl', [
  '$rootScope', '$scope', '$stateParams', 'annotationService', function($rootScope, $scope, $stateParams, annotationService) {
    $rootScope.$broadcast('navigatedTo', 'Projects');
    $scope.currentProject = _.find(annotationService.mockData, function(item) {
      return item.project.id === $stateParams.projectID;
    });
    return em.unit;
  }
]);
