// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectDetailsCtrl', [
  '$scope', '$stateParams', 'annotationService', function($scope, $stateParams, annotationService) {
    $scope.currentAnnotation = _.find(annotationService.mockData, function(item) {
      return item.project.id === parseInt($stateParams.projectID);
    });
    return em.unit;
  }
]);
