// Generated by CoffeeScript 1.4.0

Workspace.factory('toolkitService', function() {
  return [
    {
      name: 'draw',
      properties: {}
    }, {
      name: 'move',
      properties: {}
    }, {
      name: 'shape',
      properties: {},
      type: fabric.Circle,
      events: {
        mouseup: function() {},
        mousedown: function() {},
        objectadded: function() {}
      }
    }, {
      name: 'comment',
      properties: {},
      events: {
        mouseup: function() {},
        mousedown: function() {},
        objectadded: function() {}
      }
    }, {
      name: 'arrow',
      properties: {}
    }, {
      name: 'text',
      properties: {}
    }, {
      name: 'zoom',
      properties: {}
    }, {
      name: 'colorpicker',
      properties: {}
    }
  ];
});
